"""Fix user models

Revision ID: 1e726ef3d8c0
Revises: 849bf53bc496
Create Date: 2026-06-20 19:11:50.512243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e726ef3d8c0'
down_revision: Union[str, Sequence[str], None] = '849bf53bc496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('shop_name', sa.String(length=50), nullable=False),
    sa.Column('shop_contact', sa.String(length=12), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=True),
    sa.Column('gst', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_contact')
    )
    op.drop_constraint(op.f('users_shop_contact_key'), 'users', type_='unique')
    op.drop_column('users', 'gst')
    op.drop_column('users', 'shop_name')
    op.drop_column('users', 'address')
    op.drop_column('users', 'city')
    op.drop_column('users', 'shop_contact')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shop_contact', sa.VARCHAR(length=12), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('city', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('shop_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('gst', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_shop_contact_key'), 'users', ['shop_contact'], postgresql_nulls_not_distinct=False)
    op.drop_table('shops')
    # ### end Alembic commands ###
