"""added the size fixes

Revision ID: 80aeef5cd7eb
Revises: 4eed443638a5
Create Date: 2026-06-05 20:09:24.870113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80aeef5cd7eb'
down_revision: Union[str, Sequence[str], None] = '4eed443638a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gst',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gst',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
